import re

guild_text = """



<div class="image_block_content selected" id="area_1">
<div class="heading_container heading_number_2"><span class="style_only">2.</span> <h2 class="style_only" id="havoc-demon-hunter-single-target-rotation">Havoc Demon Hunter Single Target Rotation</h2></div>

<p>Havoc's single-target rotation is very closely linked to its build-and-spend
Fury loop. This uses generation tools to fuel <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_bladedance.jpg" alt="Blade Dance Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=188499" class="spell" data-wowhead="spell=188499">Blade Dance</a></span> on cooldown and
spend excess on <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_chaosstrike.jpg" alt="Chaos Strike Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=344862" class="spell" data-wowhead="spell=344862">Chaos Strike</a></span> while also using its cooldowns.</p>

<ol>
<li style="" class="rotation_line_essence_break_on">Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_glaive_1h_artifactaldrochi_d_02dual.jpg" alt="Death Sweep Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=210152" class="spell" data-wowhead="spell=210152">Death Sweep</a></span> during the <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_shadow_ritualofsacrifice.jpg" alt="Essence Break Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=258860" class="spell" data-wowhead="spell=258860">Essence Break</a></span> debuff.</li>
<li style="" class="rotation_line_essence_break_on">Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_glaive_1h_npc_d_02.jpg" alt="Annihilation Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=201427" class="spell" data-wowhead="spell=201427">Annihilation</a></span> during the <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_shadow_ritualofsacrifice.jpg" alt="Essence Break Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=258860" class="spell" data-wowhead="spell=258860">Essence Break</a></span> debuff.</li>
<details style="" class="list-item rotation_line_aldrachi_on" open="">
  <summary>
    Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_ability_aldrachireaverdemonhunter_reaversglaive.jpg" alt="Reaver's Glaive Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=442294" class="spell" data-wowhead="spell=442294">Reaver's Glaive</a></span> - <span style="color:#C373DD" class="dotted-underline"><em>Click for Rules</em></span>
  </summary>
	<ul>
	  <li>The order does not matter, but aim to have 2 stacks of <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_hunter_harass.jpg" alt="Reaver's Mark Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=442624" class="spell" data-wowhead="spell=442624">Reaver's Mark</a></span> for burst by using <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_chaosstrike.jpg" alt="Chaos Strike Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=344862" class="spell" data-wowhead="spell=344862">Chaos Strike</a></span> <strong>second</strong>.</li>
	</ul>
   </details>
<details style="" class="list-item rotation_line_inertia_on" open="">
  <summary>
    Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_felblade.jpg" alt="Felblade Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=232893" class="spell" data-wowhead="spell=232893">Felblade</a></span> with <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_10_inscription3_pigments_black.jpg" alt="Inertia Icon"> <a rel="nofollow" href="https://www.wowhead.com/ptr-2/spell=427640" class="spell" data-wowhead="spell=427640&amp;domain=ptr-2">Inertia</a></span> active to trigger it - <span style="color:#C373DD" class="dotted-underline"><em>Click for Notes</em></span>
  </summary>
    <ul>
	  <li>Avoid refreshing this if you trigger it back to back with <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_vengefulretreat2.jpg" alt="Vengeful Retreat Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=198793" class="spell" data-wowhead="spell=198793">Vengeful Retreat</a></span> and <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_ardenweald_demonhunter.jpg" alt="The Hunt Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=370965" class="spell" data-wowhead="spell=370965">The Hunt</a></span>.</li>
    </ul>
</details>
<li style="" class="rotation_line_tact_on">Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_vengefulretreat2.jpg" alt="Vengeful Retreat Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=198793" class="spell" data-wowhead="spell=198793">Vengeful Retreat</a></span> to trigger <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_rogue_surpriseattack.jpg" alt="Initiative Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=388108" class="spell" data-wowhead="spell=388108">Initiative</a></span><span style="" class="rotation_line_inertia_on"> and <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_10_inscription3_pigments_black.jpg" alt="Inertia Icon"> <a rel="nofollow" href="https://www.wowhead.com/ptr-2/spell=427640" class="spell" data-wowhead="spell=427640&amp;domain=ptr-2">Inertia</a></span></span><span style="" class="rotation_line_exergy_on"> and <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_foundryraid_demolition.jpg" alt="Exergy Icon"> <span data-wowhead="spell=206476&amp;domain=ptr-2" class="spell">Exergy</span></span></span>.</li>
<li style="" class="rotation_line_hunt_on">Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_ardenweald_demonhunter.jpg" alt="The Hunt Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=370965" class="spell" data-wowhead="spell=370965">The Hunt</a></span><span style="" class="rotation_line_inertia_on"> to trigger <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_10_inscription3_pigments_black.jpg" alt="Inertia Icon"> <a rel="nofollow" href="https://www.wowhead.com/ptr-2/spell=427640" class="spell" data-wowhead="spell=427640&amp;domain=ptr-2">Inertia</a></span></span><span style="" class="rotation_line_exergy_on"> to trigger <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_foundryraid_demolition.jpg" alt="Exergy Icon"> <span data-wowhead="spell=206476&amp;domain=ptr-2" class="spell">Exergy</span></span></span>.</li>
<li style="" class="rotation_line_felscarred_on hidden_section">Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_bossfelorcs_necromancer_red.jpg" alt="Sigil of Doom Icon"> <span data-wowhead="spell=452490" class="spell">Sigil of Doom</span></span> during <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_metamorphasisdps.jpg" alt="Metamorphosis Icon"> <span data-wowhead="spell=191427" class="spell">Metamorphosis</span></span>.</li>
<li style="" class="rotation_line_felscarred_on hidden_section">Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_fire_felfire.jpg" alt="Consuming Fire Icon"> <span data-wowhead="spell=452487" class="spell">Consuming Fire</span></span> during <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_metamorphasisdps.jpg" alt="Metamorphosis Icon"> <span data-wowhead="spell=191427" class="spell">Metamorphosis</span></span>.</li>
<li style="" class="rotation_line_essence_break_on">Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_shadow_ritualofsacrifice.jpg" alt="Essence Break Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=258860" class="spell" data-wowhead="spell=258860">Essence Break</a></span> with <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_metamorphasisdps.jpg" alt="Metamorphosis Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=191427" class="spell" data-wowhead="spell=191427">Metamorphosis</a></span> active.</li>
<li>Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_glaive_1h_artifactaldrochi_d_02dual.jpg" alt="Death Sweep Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=210152" class="spell" data-wowhead="spell=210152">Death Sweep</a></span>.</li>
<li style="" class="rotation_line_afi_on">Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_immolation.jpg" alt="Immolation Aura Icon"> <span data-wowhead="spell=258920" class="spell">Immolation Aura</span></span><span style="" class="rotation_line_felscarred_on hidden_section"> / <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_fire_felfire.jpg" alt="Consuming Fire Icon"> <span data-wowhead="spell=452487" class="spell">Consuming Fire</span></span></span> if at 2 charges.</li>
<li style="" class="rotation_line_spite_on">Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_bastion_demonhunter.jpg" alt="Sigil of Spite Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=390163" class="spell" data-wowhead="spell=390163">Sigil of Spite</a></span><span style="" class="rotation_line_aldrachi_on"> to generate Souls</span>.</li>
<details style="" class="list-item rotation_line_felscarred_on rotation_line_student_on hidden_section">
  <summary>
    Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_sigilofinquisition.jpg" alt="Sigil of Flame Icon"> <span data-wowhead="spell=204596" class="spell">Sigil of Flame</span></span> before <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_eyebeam.jpg" alt="Eye Beam Icon"> <span data-wowhead="spell=198013" class="spell">Eye Beam</span></span> to trigger <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/achievement_dungeon_theatreofpain_kultharok.jpg" alt="Student of Suffering Icon"> <span data-wowhead="spell=452412" class="spell">Student of Suffering</span></span> - <span style="color:#C373DD" class="dotted-underline"><em>Click for Notes</em></span>
  </summary>
	 <ul>
	   <li>Hold this for 10 seconds every cycle to align them with <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_ironmaidens_whirlofblood.jpg" alt="Cycle of Hatred Icon"> <span data-wowhead="spell=258887" class="spell">Cycle of Hatred</span></span>.</li>
	 </ul>
   </details>
<details style="" class="list-item rotation_line_felscarred_on hidden_section">
  <summary>
    Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_shadow_demonicfortitude.jpg" alt="Abyssal Gaze Icon"> <span data-wowhead="spell=452497" class="spell">Abyssal Gaze</span></span> with <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_fire_felhellfire.jpg" alt="Demonsurge Icon"> <span data-wowhead="spell=469995&amp;domain=ptr-2" class="spell">Demonsurge</span></span> active - <span style="color:#C373DD" class="dotted-underline"><em>Click for Notes</em></span>
  </summary>
	 <ul>
	   <li class="rotation_line_felscarred_on hidden_section">Avoid extending <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_metamorphasisdps.jpg" alt="Metamorphosis Icon"> <span data-wowhead="spell=191427" class="spell">Metamorphosis</span></span> through this outside of the <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_fire_felhellfire.jpg" alt="Demonsurge Icon"> <span data-wowhead="spell=469995&amp;domain=ptr-2" class="spell">Demonsurge</span></span> proc, to avoid wasting extra triggers from <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_eyebeam.jpg" alt="Eye Beam Icon"> <span data-wowhead="spell=198013" class="spell">Eye Beam</span></span>.</li>
	 </ul>
</details>
<li>Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_eyebeam.jpg" alt="Eye Beam Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=198013" class="spell" data-wowhead="spell=198013">Eye Beam</a></span>.</li>
<li>Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_metamorphasisdps.jpg" alt="Metamorphosis Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=191427" class="spell" data-wowhead="spell=191427">Metamorphosis</a></span> <span class="rotation_line_chaotic_on">if <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_eyebeam.jpg" alt="Eye Beam Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=198013" class="spell" data-wowhead="spell=198013">Eye Beam</a></span> and <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_glaive_1h_artifactaldrochi_d_02dual.jpg" alt="Death Sweep Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=210152" class="spell" data-wowhead="spell=210152">Death Sweep</a></span> are on cooldown</span>.</li>
<li>Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_bladedance.jpg" alt="Blade Dance Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=188499" class="spell" data-wowhead="spell=188499">Blade Dance</a></span>.</li>
<li>Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_glaive_1h_npc_d_02.jpg" alt="Annihilation Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=201427" class="spell" data-wowhead="spell=201427">Annihilation</a></span>.</li>
<li>Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_felblade.jpg" alt="Felblade Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=232893" class="spell" data-wowhead="spell=232893">Felblade</a></span> if under 80 Fury.</li>
<li style="" class="rotation_line_aldrachi_on">Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_sigilofinquisition.jpg" alt="Sigil of Flame Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=204596" class="spell" data-wowhead="spell=204596">Sigil of Flame</a></span> if under 90 Fury.</li>
<li style="" class="rotation_line_felscarred_on rotation_line_student_off hidden_section">Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_sigilofinquisition.jpg" alt="Sigil of Flame Icon"> <span data-wowhead="spell=204596" class="spell">Sigil of Flame</span></span> if under 90 Fury.</li>
<li>Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_chaosstrike.jpg" alt="Chaos Strike Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=344862" class="spell" data-wowhead="spell=344862">Chaos Strike</a></span>.</li>
<li>Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_immolation.jpg" alt="Immolation Aura Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=258920" class="spell" data-wowhead="spell=258920">Immolation Aura</a></span>.</li>
<li>Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_throwglaive.jpg" alt="Throw Glaive Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=185123" class="spell" data-wowhead="spell=185123">Throw Glaive</a></span> or <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_felrush.jpg" alt="Fel Rush Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=344865" class="spell" data-wowhead="spell=344865">Fel Rush</a></span> to fill.</li>
</ol>

<p>Havoc's gameplay loop is <em>heavily</em> influenced by your talent selections
due to the number of rotationally warping effects. What you pick dictates what
is important to prioritize, with the overarching goal of aligning buffs for big
payoff moments. Some key details are:</p>

<ul>
<li style="" class="rotation_line_aldrachi_on"><span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_ability_aldrachireaverdemonhunter_reaversglaive.jpg" alt="Reaver's Glaive Icon"> <span data-wowhead="spell=442294" class="spell">Reaver's Glaive</span></span>
is an <em>extremely</em> high priority press to make sure you can maintain
<span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_hunter_harass.jpg" alt="Reaver's Mark Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=442624" class="spell" data-wowhead="spell=442624">Reaver's Mark</a></span>. The order you consume <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_ability_aldrachireaverdemonhunter_reaversglaive.jpg" alt="Art of the Glaive Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=442290" class="spell" data-wowhead="spell=442290">Art of the Glaive</a></span> does not matter
much as the mark stacks. Aim to consume <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_chaosstrike.jpg" alt="Chaos Strike Icon"> <span data-wowhead="spell=344862" class="spell">Chaos Strike</span></span> second during burst
windows to be sure.</li>
<li style="" class="rotation_line_aldrachi_on">Use <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_ardenweald_demonhunter.jpg" alt="The Hunt Icon"> <span data-wowhead="spell=370965" class="spell">The Hunt</span></span>
to snap generate <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_ability_aldrachireaverdemonhunter_reaversglaive.jpg" alt="Reaver's Glaive Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=442294" class="spell" data-wowhead="spell=442294">Reaver's Glaive</a></span> at the start of the pull of whenever you
need it.<span style="" class="rotation_line_spite_on"> Additionally, you
should use <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_bastion_demonhunter.jpg" alt="Sigil of Spite Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=390163" class="spell" data-wowhead="spell=390163">Sigil of Spite</a></span> for a burst of 3 Souls to help cycle to your next
cast</span>.</li>
<li style="" class="rotation_line_felscarred_on hidden_section"><span class="spell_icon_span inline_hero_talent" style="color:#48D272;"><img class="spell_icon" alt="" src="//static.icy-veins.com/images/wow/tools/hero-talents/fel-scarred.webp"> Fel-Scarred</span>
builds place a lot of emphasis on your 40-second and 2-minute burst windows, making
sure to always consume available <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_fire_felhellfire.jpg" alt="Demonsurge Icon"> <span data-wowhead="spell=469995&amp;domain=ptr-2" class="spell">Demonsurge</span></span> procs. Otherwise, it cycles
Fury to get as much value out of <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_glaive_1h_artifactazgalor_d_02dual.jpg" alt="Burning Blades Icon"> <span data-wowhead="spell=452408" class="spell">Burning Blades</span></span> as possible.</li>
<li style="" class="rotation_line_felscarred_on hidden_section">With <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/achievement_dungeon_theatreofpain_kultharok.jpg" alt="Student of Suffering Icon"> <span data-wowhead="spell=452412" class="spell">Student of Suffering</span></span>
taken as <span class="spell_icon_span inline_hero_talent" style="color:#48D272;"><img class="spell_icon" alt="" src="//static.icy-veins.com/images/wow/tools/hero-talents/fel-scarred.webp"> Fel-Scarred</span>, you also ideally want to hold your <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_sigilofinquisition.jpg" alt="Sigil of Flame Icon"> <span data-wowhead="spell=204596" class="spell">Sigil of Flame</span></span>
to cast it just before each <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_eyebeam.jpg" alt="Eye Beam Icon"> <span data-wowhead="spell=198013" class="spell">Eye Beam</span></span> to enhance your burst windows.</li>
<li><span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_eyebeam.jpg" alt="Eye Beam Icon"> <span data-wowhead="spell=198013" class="spell">Eye Beam</span></span> is still always used in single-target as an entry point into
<span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_shadow_demonform.jpg" alt="Demonic Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=213410" class="spell" data-wowhead="spell=213410">Demonic</a></span>. The frequency will get faster as the encounter progresses due to
<span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_ironmaidens_whirlofblood.jpg" alt="Cycle of Hatred Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=258887" class="spell" data-wowhead="spell=258887">Cycle of Hatred</a></span>, down to every 20 seconds.</li>
<li style="" class="rotation_line_tact_on">With <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_vengefulretreat2.jpg" alt="Tactical Retreat Icon"> <span data-wowhead="spell=389688" class="spell">Tactical Retreat</span></span>,
when using your <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_metamorphasisdps.jpg" alt="Metamorphosis Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=191427" class="spell" data-wowhead="spell=191427">Metamorphosis</a></span> cooldown you can use it to animation cancel
the leap backward and stick to your target.</li>
<li style="" class="rotation_line_essence_break_on">Your
<span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_shadow_ritualofsacrifice.jpg" alt="Essence Break Icon"> <span data-wowhead="spell=258860" class="spell">Essence Break</span></span> windows are a key burst moment. You should always aim to
overlap this with your <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_metamorphasisdps.jpg" alt="Metamorphosis Icon"> <span data-wowhead="spell=191427" class="spell">Metamorphosis</span></span> effect <span class="rotation_line_intertia_off hidden_section">alongside
<span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_rogue_surpriseattack.jpg" alt="Initiative Icon"> <span data-wowhead="spell=388108" class="spell">Initiative</span></span></span><span class="rotation_line_inertia_on">alongside
<span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_rogue_surpriseattack.jpg" alt="Initiative Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=388108" class="spell" data-wowhead="spell=388108">Initiative</a></span> / <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_10_inscription3_pigments_black.jpg" alt="Inertia Icon"> <a rel="nofollow" href="https://www.wowhead.com/ptr-2/spell=427640" class="spell" data-wowhead="spell=427640&amp;domain=ptr-2">Inertia</a></span></span> and fit in at least one <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_glaive_1h_artifactaldrochi_d_02dual.jpg" alt="Death Sweep Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=210152" class="spell" data-wowhead="spell=210152">Death Sweep</a></span>
and two <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_glaive_1h_npc_d_02.jpg" alt="Annihilation Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=201427" class="spell" data-wowhead="spell=201427">Annihilation</a></span> casts.</li>
<li style="" class="rotation_line_inertia_on"><span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_10_inscription3_pigments_black.jpg" alt="Inertia Icon"> <span data-wowhead="spell=427640&amp;domain=ptr-2" class="spell">Inertia</span></span>
provides extra burst windows to play around. These should <em>always</em> aim to be
overlapped with your <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_eyebeam.jpg" alt="Eye Beam Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=198013" class="spell" data-wowhead="spell=198013">Eye Beam</a></span>, <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_shadow_ritualofsacrifice.jpg" alt="Essence Break Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=258860" class="spell" data-wowhead="spell=258860">Essence Break</a></span> and <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_ardenweald_demonhunter.jpg" alt="The Hunt Icon"> <span data-wowhead="spell=370965" class="spell">The Hunt</span></span>
casts. Uptime is limited by <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_vengefulretreat2.jpg" alt="Vengeful Retreat Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=198793" class="spell" data-wowhead="spell=198793">Vengeful Retreat</a></span> and <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_ardenweald_demonhunter.jpg" alt="The Hunt Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=370965" class="spell" data-wowhead="spell=370965">The Hunt</a></span>, but
cooldowns will naturally align using <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_ironmaidens_whirlofblood.jpg" alt="Cycle of Hatred Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=258887" class="spell" data-wowhead="spell=258887">Cycle of Hatred</a></span>.</li>
<li style="" class="rotation_line_afi_on">When playing <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_chaoticimprint_fire.jpg" alt="A Fire Inside Icon"> <span data-wowhead="spell=427775&amp;domain=ptr-2" class="spell">A Fire Inside</span></span>, you
want to make sure it is always under 2 charges to avoid wasting uses throughout a
fight.</li>
</ul>

</div>




<div class="image_block_content selected" id="area_2">

<div class="heading_container heading_number_2"><span class="style_only">2.</span> <h2 class="style_only" id="havoc-demon-hunter-aoe-rotation">Havoc Demon Hunter AoE Rotation</h2></div>

<p>Havoc's gameplay does not drastically change in AoE due to the large amount
of passive AoE many of its rotational abilities do. Instead, it deals priority
damage while cleaving from it:</p>

<ol>
<li style="" class="rotation_line_essence_break_on">Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_glaive_1h_artifactaldrochi_d_02dual.jpg" alt="Death Sweep Icon"> <span data-wowhead="spell=210152" class="spell">Death Sweep</span></span> during the <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_shadow_ritualofsacrifice.jpg" alt="Essence Break Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=258860" class="spell" data-wowhead="spell=258860">Essence Break</a></span> debuff.</li>
<li style="" class="rotation_line_essence_break_on">Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_glaive_1h_npc_d_02.jpg" alt="Annihilation Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=201427" class="spell" data-wowhead="spell=201427">Annihilation</a></span> during the <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_shadow_ritualofsacrifice.jpg" alt="Essence Break Icon"> <span data-wowhead="spell=258860" class="spell">Essence Break</span></span> debuff.</li>
<details style="" class="list-item rotation_line_aldrachi_on" open="">
  <summary>
    Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_ability_aldrachireaverdemonhunter_reaversglaive.jpg" alt="Reaver's Glaive Icon"> <span data-wowhead="spell=442294" class="spell">Reaver's Glaive</span></span> - <span style="color:#C373DD" class="dotted-underline"><em>Click for Rules</em></span>
  </summary>
	 <ul>
	   <li class="rotation_line_aldrachi_on">Make sure to cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_chaosstrike.jpg" alt="Chaos Strike Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=344862" class="spell" data-wowhead="spell=344862">Chaos Strike</a></span> / <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_glaive_1h_npc_d_02.jpg" alt="Annihilation Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=201427" class="spell" data-wowhead="spell=201427">Annihilation</a></span> before your next <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_bladedance.jpg" alt="Blade Dance Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=188499" class="spell" data-wowhead="spell=188499">Blade Dance</a></span> / <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_glaive_1h_artifactaldrochi_d_02dual.jpg" alt="Death Sweep Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=210152" class="spell" data-wowhead="spell=210152">Death Sweep</a></span> to empower <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_fire_felflamestrike.jpg" alt="Fury of the Aldrachi Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=442718" class="spell" data-wowhead="spell=442718">Fury of the Aldrachi</a></span>.</li>
	 </ul>
</details>
<details style="" class="list-item rotation_line_inertia_on" open="">
  <summary>
    Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_felrush.jpg" alt="Fel Rush Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=344865" class="spell" data-wowhead="spell=344865">Fel Rush</a></span> / <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_felblade.jpg" alt="Felblade Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=232893" class="spell" data-wowhead="spell=232893">Felblade</a></span> with <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_10_inscription3_pigments_black.jpg" alt="Inertia Icon"> <a rel="nofollow" href="https://www.wowhead.com/ptr-2/spell=427640" class="spell" data-wowhead="spell=427640&amp;domain=ptr-2">Inertia</a></span> active to trigger it - <span style="color:#C373DD" class="dotted-underline"><em>Click for Notes</em></span>
  </summary>
	 <ul>
	   <li class="rotation_line_inertia_on">Avoid refreshing this if you trigger it back to back with <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_vengefulretreat2.jpg" alt="Vengeful Retreat Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=198793" class="spell" data-wowhead="spell=198793">Vengeful Retreat</a></span> and <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_ardenweald_demonhunter.jpg" alt="The Hunt Icon"> <span data-wowhead="spell=370965" class="spell">The Hunt</span></span>.</li>
	 </ul>
</details>
<li style="" class="rotation_line_afi_on rotation_line_aldrachi_on">Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_immolation.jpg" alt="Immolation Aura Icon"> <span data-wowhead="spell=258920" class="spell">Immolation Aura</span></span> if at 2 charges.</li>
<details style="" class="list-item rotation_line_afi_on rotation_line_felscarred_on hidden_section">
  <summary>
    Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_immolation.jpg" alt="Immolation Aura Icon"> <span data-wowhead="spell=258920" class="spell">Immolation Aura</span></span> / <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_fire_felfire.jpg" alt="Consuming Fire Icon"> <span data-wowhead="spell=452487" class="spell">Consuming Fire</span></span> if at 2 charges - <span style="color:#C373DD" class="dotted-underline"><em><span style="color:#48D272">Fel-Scarred</span> Notes</em></span>
  </summary>
    <ul>
	  <li class="rotation_line_felscarred_on hidden_section">If you are about to cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_metamorphasisdps.jpg" alt="Metamorphosis Icon"> <span data-wowhead="spell=191427" class="spell">Metamorphosis</span></span>, recast this until it reaches 0 charges.</li>
    </ul>
</details>
<li style="" class="rotation_line_initiative_on">Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_vengefulretreat2.jpg" alt="Vengeful Retreat Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=198793" class="spell" data-wowhead="spell=198793">Vengeful Retreat</a></span> to trigger <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_rogue_surpriseattack.jpg" alt="Initiative Icon"> <span data-wowhead="spell=388108" class="spell">Initiative</span></span><span style="" class="rotation_line_inertia_on"> and <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_10_inscription3_pigments_black.jpg" alt="Inertia Icon"> <a rel="nofollow" href="https://www.wowhead.com/ptr-2/spell=427640" class="spell" data-wowhead="spell=427640&amp;domain=ptr-2">Inertia</a></span></span><span style="" class="rotation_line_exergy_on"> and <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_foundryraid_demolition.jpg" alt="Exergy Icon"> <span data-wowhead="spell=206476&amp;domain=ptr-2" class="spell">Exergy</span></span></span>.</li>
<li style="" class="rotation_line_hunt_on">Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_ardenweald_demonhunter.jpg" alt="The Hunt Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=370965" class="spell" data-wowhead="spell=370965">The Hunt</a></span><span style="" class="rotation_line_inertia_on"> and <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_10_inscription3_pigments_black.jpg" alt="Inertia Icon"> <a rel="nofollow" href="https://www.wowhead.com/ptr-2/spell=427640" class="spell" data-wowhead="spell=427640&amp;domain=ptr-2">Inertia</a></span></span><span style="" class="rotation_line_exergy_on"> and <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_foundryraid_demolition.jpg" alt="Exergy Icon"> <span data-wowhead="spell=206476&amp;domain=ptr-2" class="spell">Exergy</span></span></span>.</li>
<li>Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_immolation.jpg" alt="Immolation Aura Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=258920" class="spell" data-wowhead="spell=258920">Immolation Aura</a></span><span style="" class="rotation_line_felscarred_on hidden_section"> / <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_fire_felfire.jpg" alt="Consuming Fire Icon"> <span data-wowhead="spell=452487" class="spell">Consuming Fire</span></span></span>.</li>
<li style="" class="rotation_line_felscarred_on hidden_section">Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_bossfelorcs_necromancer_red.jpg" alt="Sigil of Doom Icon"> <span data-wowhead="spell=452490" class="spell">Sigil of Doom</span></span>.</li>
<li style="" class="rotation_line_essence_break_on">Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_shadow_ritualofsacrifice.jpg" alt="Essence Break Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=258860" class="spell" data-wowhead="spell=258860">Essence Break</a></span> with <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_metamorphasisdps.jpg" alt="Metamorphosis Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=191427" class="spell" data-wowhead="spell=191427">Metamorphosis</a></span> active.</li>
<li>Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_glaive_1h_artifactaldrochi_d_02dual.jpg" alt="Death Sweep Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=210152" class="spell" data-wowhead="spell=210152">Death Sweep</a></span>.</li>
<li style="" class="rotation_line_spite_on">Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_bastion_demonhunter.jpg" alt="Sigil of Spite Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=390163" class="spell" data-wowhead="spell=390163">Sigil of Spite</a></span><span style="" class="rotation_line_aldrachi_on"> to generate Souls</span>.</li>
<details style="" class="list-item rotation_line_felscarred_on rotation_line_student_on hidden_section">
  <summary>
    Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_sigilofinquisition.jpg" alt="Sigil of Flame Icon"> <span data-wowhead="spell=204596" class="spell">Sigil of Flame</span></span> to trigger <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/achievement_dungeon_theatreofpain_kultharok.jpg" alt="Student of Suffering Icon"> <span data-wowhead="spell=452412" class="spell">Student of Suffering</span></span> - <span style="color:#C373DD" class="dotted-underline"><em>Click for Notes</em></span>
  </summary>
    <ul>
	  <li class="rotation_line_felscarred_on rotation_line_student_on hidden_section">Hold this for 10 seconds every cycle to align them with <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_ironmaidens_whirlofblood.jpg" alt="Cycle of Hatred Icon"> <span data-wowhead="spell=258887" class="spell">Cycle of Hatred</span></span>.</li>
	</ul>
   </details>
<li style="" class="rotation_line_aldrachi_on">Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_eyebeam.jpg" alt="Eye Beam Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=198013" class="spell" data-wowhead="spell=198013">Eye Beam</a></span>.</li>
<details style="" class="list-item rotation_line_felscarred_on hidden_section">
  <summary>
    Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_eyebeam.jpg" alt="Eye Beam Icon"> <span data-wowhead="spell=198013" class="spell">Eye Beam</span></span> / <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_shadow_demonicfortitude.jpg" alt="Abyssal Gaze Icon"> <span data-wowhead="spell=452497" class="spell">Abyssal Gaze</span></span> - <span style="color:#C373DD" class="dotted-underline"><em>Click for Notes</em></span>
  </summary>
	<ul>
	  <li class="rotation_line_felscarred_on hidden_section">Avoid extending <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_metamorphasisdps.jpg" alt="Metamorphosis Icon"> <span data-wowhead="spell=191427" class="spell">Metamorphosis</span></span> through this outside of the <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_fire_felhellfire.jpg" alt="Demonsurge Icon"> <span data-wowhead="spell=469995&amp;domain=ptr-2" class="spell">Demonsurge</span></span> proc, to avoid wasting extra triggers from <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_eyebeam.jpg" alt="Eye Beam Icon"> <span data-wowhead="spell=198013" class="spell">Eye Beam</span></span>.</li>
	</ul>
</details>
<li>Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_metamorphasisdps.jpg" alt="Metamorphosis Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=191427" class="spell" data-wowhead="spell=191427">Metamorphosis</a></span> if <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_eyebeam.jpg" alt="Eye Beam Icon"> <span data-wowhead="spell=198013" class="spell">Eye Beam</span></span><span style="" class="rotation_line_felscarred_on hidden_section">, <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_sigilofinquisition.jpg" alt="Sigil of Flame Icon"> <span data-wowhead="spell=204596" class="spell">Sigil of Flame</span></span>, <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_immolation.jpg" alt="Immolation Aura Icon"> <span data-wowhead="spell=258920" class="spell">Immolation Aura</span></span></span> and <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_glaive_1h_artifactaldrochi_d_02dual.jpg" alt="Death Sweep Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=210152" class="spell" data-wowhead="spell=210152">Death Sweep</a></span> are on cooldown.</li>
<li>Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_bladedance.jpg" alt="Blade Dance Icon"> <span data-wowhead="spell=188499" class="spell">Blade Dance</span></span>.</li>
<li>Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_glaive_1h_npc_d_02.jpg" alt="Annihilation Icon"> <span data-wowhead="spell=201427" class="spell">Annihilation</span></span>.</li>
<li style="" class="rotation_line_aldrachi_on">Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_sigilofinquisition.jpg" alt="Sigil of Flame Icon"> <span data-wowhead="spell=204596" class="spell">Sigil of Flame</span></span> if under 90 Fury.</li>
<li>Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_felblade.jpg" alt="Felblade Icon"> <span data-wowhead="spell=232893" class="spell">Felblade</span></span> if under 80 Fury.</li>
<li>Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_chaosstrike.jpg" alt="Chaos Strike Icon"> <span data-wowhead="spell=344862" class="spell">Chaos Strike</span></span>.</li>
<li>Cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_throwglaive.jpg" alt="Throw Glaive Icon"> <span data-wowhead="spell=185123" class="spell">Throw Glaive</span></span> or <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_felrush.jpg" alt="Fel Rush Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=344865" class="spell" data-wowhead="spell=344865">Fel Rush</a></span> to fill.</li>
</ol>

<p>The majority of tools you make use of in single-target apply directly to
AoE, with the exception of <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_glaive_1h_npc_d_02.jpg" alt="Annihilation Icon"> <span data-wowhead="spell=201427" class="spell">Annihilation</span></span> / <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_chaosstrike.jpg" alt="Chaos Strike Icon"> <span data-wowhead="spell=344862" class="spell">Chaos Strike</span></span> which
fall much further down the priority. Your focus depends on which key AoE
talents you have taken, and notes based on your selection in the talent
switches are:</p>

<ul>
<li style="" class="rotation_line_aldrachi_on"><span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_ability_aldrachireaverdemonhunter_reaversglaive.jpg" alt="Reaver's Glaive Icon"> <span data-wowhead="spell=442294" class="spell">Reaver's Glaive</span></span>
is an <em>extremely</em> high-priority press due to the high damage and the need
to maintain <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_arcane_arcanetactics.jpg" alt="Thrill of the Fight Icon"> <span data-wowhead="spell=442686" class="spell">Thrill of the Fight</span></span>. Make sure to always consume the
<span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_bladedance.jpg" alt="Blade Dance Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=188499" class="spell" data-wowhead="spell=188499">Blade Dance</a></span> buff second to empower it.</li>
<li style="" class="rotation_line_aldrachi_on">Use <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_ardenweald_demonhunter.jpg" alt="The Hunt Icon"> <span data-wowhead="spell=370965" class="spell">The Hunt</span></span>
to snap generate <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_ability_aldrachireaverdemonhunter_reaversglaive.jpg" alt="Reaver's Glaive Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=442294" class="spell" data-wowhead="spell=442294">Reaver's Glaive</a></span> at the start of the pull of whenever you
need it.<span style="" class="rotation_line_spite_on"> Additionally, you
should use <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_bastion_demonhunter.jpg" alt="Sigil of Spite Icon"> <span data-wowhead="spell=390163" class="spell">Sigil of Spite</span></span> for a burst of 4 Souls to help cycle to your next
cast.</span>.</li>
<li style="" class="rotation_line_felscarred_on hidden_section"><span class="spell_icon_span inline_hero_talent" style="color:#48D272;"><img class="spell_icon" alt="" src="//static.icy-veins.com/images/wow/tools/hero-talents/fel-scarred.webp"> Fel-Scarred</span>
builds deal <em>extremely</em> high 2-minute burst with <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_metamorphasisdps.jpg" alt="Metamorphosis Icon"> <span data-wowhead="spell=191427" class="spell">Metamorphosis</span></span>.
Make sure to plan around these moments to maximize your burst with <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_fire_felhellfire.jpg" alt="Demonsurge Icon"> <span data-wowhead="spell=469995&amp;domain=ptr-2" class="spell">Demonsurge</span></span>
and empowered abilities.</li>
<li style="" class="rotation_line_felscarred_on hidden_section">If you are playing
<span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/achievement_dungeon_theatreofpain_kultharok.jpg" alt="Student of Suffering Icon"> <span data-wowhead="spell=452412" class="spell">Student of Suffering</span></span> in an AoE situation, you should still be holding
<span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_sigilofinquisition.jpg" alt="Sigil of Flame Icon"> <span data-wowhead="spell=204596" class="spell">Sigil of Flame</span></span> for 10 seconds each cycle to align it with <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_eyebeam.jpg" alt="Eye Beam Icon"> <span data-wowhead="spell=198013" class="spell">Eye Beam</span></span>.</li>
<li><span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_immolation.jpg" alt="Immolation Aura Icon"> <span data-wowhead="spell=258920" class="spell">Immolation Aura</span></span> is a core component of AoE. The biggest of
these is <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_fire_fireballgreen.jpg" alt="Ragefire Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=388107" class="spell" data-wowhead="spell=388107">Ragefire</a></span>, and when playing this you need to be aware of the
expiry time to make sure it hits targets.<span style="" class="rotation_line_afi_on"> With <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_chaoticimprint_fire.jpg" alt="A Fire Inside Icon"> <span data-wowhead="spell=427775&amp;domain=ptr-2" class="spell">A Fire Inside</span></span>,
your access to this is much higher and you should avoid ever hitting 2 charges.</span><span style="" class="rotation_line_felscarred_on hidden_section"> With
<span class="spell_icon_span inline_hero_talent" style="color:#48D272;"><img class="spell_icon" alt="" src="//static.icy-veins.com/images/wow/tools/hero-talents/fel-scarred.webp"> Fel-Scarred</span> talents, you also need to <em>make sure</em> it
is <span style="" class="rotation_line_afi_on">at 0 charges</span><span style="" class="rotation_line_afi_off hidden_section">on cooldown</span> before
casting <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_metamorphasisdps.jpg" alt="Metamorphosis Icon"> <span data-wowhead="spell=191427" class="spell">Metamorphosis</span></span> to reset its cooldown.</span></li>
<li style="" class="rotation_line_inertia_on">You should always aim
to cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_vengefulretreat2.jpg" alt="Vengeful Retreat Icon"> <span data-wowhead="spell=198793" class="spell">Vengeful Retreat</span></span> and <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_ardenweald_demonhunter.jpg" alt="The Hunt Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=370965" class="spell" data-wowhead="spell=370965">The Hunt</a></span> on cooldown when playing
<span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_10_inscription3_pigments_black.jpg" alt="Inertia Icon"> <span data-wowhead="spell=427640&amp;domain=ptr-2" class="spell">Inertia</span></span>, overlapping these buffs with your other cooldowns. Make sure not
to overwrite an existing <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_10_inscription3_pigments_black.jpg" alt="Inertia Icon"> <span data-wowhead="spell=427640&amp;domain=ptr-2" class="spell">Inertia</span></span> window if you cast these back-to-back.</li>
<li style="" class="rotation_line_exergy_on">You should always aim
to cast <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_vengefulretreat2.jpg" alt="Vengeful Retreat Icon"> <span data-wowhead="spell=198793" class="spell">Vengeful Retreat</span></span> and <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_ardenweald_demonhunter.jpg" alt="The Hunt Icon"> <span data-wowhead="spell=370965" class="spell">The Hunt</span></span> on cooldown when playing
<span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_foundryraid_demolition.jpg" alt="Exergy Icon"> <span data-wowhead="spell=206476&amp;domain=ptr-2" class="spell">Exergy</span></span>. The buff has a 30-second max duration, so it should have 100%
uptime if used correctly.</li>
<li style="" class="rotation_line_fbarr_on"><span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_felbarrage.jpg" alt="Fel Barrage Icon"> <span data-wowhead="spell=258925" class="spell">Fel Barrage</span></span> in AoE
requires you to plan for the 256 Fury required to get a full 8-second cast. While
it is active, avoid spending Fury on <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_glaive_1h_npc_d_02.jpg" alt="Annihilation Icon"> <span data-wowhead="spell=201427" class="spell">Annihilation</span></span> and try to generate
instead.</li>
<li style="" class="rotation_line_essence_break_on"><span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/spell_shadow_ritualofsacrifice.jpg" alt="Essence Break Icon"> <span data-wowhead="spell=258860" class="spell">Essence Break</span></span>
should always be layered over your <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/ability_demonhunter_metamorphasisdps.jpg" alt="Metamorphosis Icon"> <span data-wowhead="spell=191427" class="spell">Metamorphosis</span></span> effect. Make sure to cast
one <span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_glaive_1h_artifactaldrochi_d_02dual.jpg" alt="Death Sweep Icon"> <span data-wowhead="spell=210152" class="spell">Death Sweep</span></span>, but the remaining time it is not as essential to cast
<span class="spell_icon_span"><img class="spell_icon" src="//static.icy-veins.com/images/wow/large_icons/inv_glaive_1h_npc_d_02.jpg" alt="Annihilation Icon"> <a rel="nofollow" href="https://www.wowhead.com/spell=201427" class="spell" data-wowhead="spell=201427">Annihilation</a></span>s.</li>
</ul>

</div>








"""


def extract_spell_id(html: str) -> list[int]:
    """
    Extract spell IDs from HTML string containing data-wowhead attributes.

    Args:
        html: Input HTML string to parse

    Returns:
        list[int]: List of extracted spell IDs
    """
    pattern = r'data-wowhead\s*=\s*["\'].*?spell=(\d+).*?["\']'
    matches = re.findall(pattern, html)
    return [int(m) for m in matches]


if __name__ == "__main__":
    spell_list = extract_spell_id(guild_text)
    spell_list = list(set(spell_list))
    print(spell_list)
